stages:
  - test
  - deploy

test:
  image: node:lts
  stage: test
  before_script:
    - npm i
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

deploy_registry:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || :
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest --label "git-ref=$CI_COMMIT_SHORT_SHA build-date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA && docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master