stages:
  - test
  - deploy

test:
  image: node:lts
  stage: test
  before_script:
    - npm ci
  script:
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

deploy_registry:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull --label "git-ref=$CI_COMMIT_SHORT_SHA" --label "build-date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA" && docker push "${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA"
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master