language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm i
script:
  - npm test
branches:
  only:
    - master
    - /^feature-.*/
after_success:
  - npm i codecov && codecov
