language: node_js
node_js:
  - node
env:
  global:
    - secure: lrqIuzoJjZHVQLev7hMkT4KohoFMg0DoobMJsdLertix5FPwoqJpWZXpWPswZKnQrPaOB6dvJ6fhQ1kouCHt2DpB+gdE8SdIKpfotEZO89no1R+sDCJOZRVJ83uLKX8+tpzzD/jXPyqce5qRE/JGvlwSZLGyYu9l+syzr1hVj44p7UARuC5mA+OMLPw+V1OPz0ayL0+4WoGEjBFUJzsEnNNEnSbGzRQVIouKL2/k+cVgAAqiMqwne4NT+YmRQGFKNyC+ZREV42TWb5as+5fxlvixLlL0olzIxZSuE0JgnHeVNlihCcnGiom/8P6Zi9Kc0AauUX5UVw5oKZtqlou6S3p4yAjbm+6U72ErQpt8yKmSDxzcJBOluPSeFd56d2Z4dNQaEspMGv2OzvyuUXUARcLxgIaOqaVjrz9uhsaq5w/hCSu+Gy4GS+NNXtRYSzgin9rxH2iW6XYr6B7qByNGC5ozsgSP0MyWi7ChMhQI4WktKpoBNiUsHvrbUFyJSJk72LUCzwX1Fcx1tqoUKpJ8ST35WQ33WqoWmFMDe7OKKngBfaxwaBfGywTr9LtKjwg6jgZgVCIzmHOyk76ZYtWQLBeyMNsHULhnENGv4IrYba8AkhTcNjTaShG5nkmUCcdAWNjyUHMavTUA1+klBhb82WG/Eq2LYK/24cD3dutkw2g=
    - secure: hN52EtCBBtEnRYgvPDzD1nrZBwOCmrHyt7hl6WCwGSzEExnXzi9NdEMLZkhMRJmdqVrO4/YsDDFsOl8X5fHII5WNV5r7CVRK4eT8aOcshdjQ+NhO+DFJDx1sBs+bOGg4Np7Jtl3/gQv7WeeKZtgK3ThzlvDJPnbzfiNc3XxxF/ld6M0r1cEUU/qGoWVNQ5KioI0m4nxgFEGGEXSX4iY3OanTIRBUjaldmfLVEcixMuGRy0lISZH5D+v8Nln6TZt9D1xPJ77MNtVIiKdrXBmBzYfbxQFVDll75hg+SbHfDSHxUtAcUOnLVWzVA0wseCCyw8UZXD/GXo3PlAncgb7i8p9r/+3LGR3E5/KNNYODc7jQ1WNIDl7Z/nl+eEcYA1rcw/t6rHXYMWW3qLjxTukxpwEfbPvAKy2ewP2F318SKDzp5bmPw0ghbpQSWSTp/iH4MfZQyUCLDoa8wc3drf4aUlY52I5D9RRwIWuxMqBveRUC7LQYXV6aKWzKhQsy/YZa4ZlSMWU5u77qjIr98NqwdSXzxyl5b7sjOomIHTayh9Ddlns3yjpCVTQbx9RmpcPfcI1I6qDNmUdi3wYjmLX2Xayb/wqOinghVX2sK4rgs/ik8F0R83fF32AKa7BxaaokJXN8P8xuUrIr+85OPftwasHgvTxrBbXUUv8+NXl2lvc=
    - secure: H15xBFEWOK5+le1aOQwcWzIFOv4eryEBzh7UOP6Dz7g0mHGf6yrOYNdq5ePSMcNz9dgmqVKyxd8vKxOhlVju8M24CNukOvVgNwCsYC2ITsAaC+MTd/PI39BpTQMjrcH02VEw92dtAoay9WBruAARNHlX92OMyRDhRwf50IR7teR3SiHC7n7YjvSYFZe7fnZnxHjxwNTyJzBjx19q2YAgcToJxm2xjpHQ1Q8AMDYUudy37PpQUYsMiNGZc7rXQA3B2ZfRkM+aAR+dtNxdOK3q/ukUbVXCaJR8DXEqdgmgBP7OGUKqJRU4BG/+qe/QQGUzAv9w0pwxgPmrTmAR72u5jeKlVSJmXFBIZP+vv/p6bVIKsasvKjmg4jUBUUq8D4l/dlJbFiXa1SRbptpIy83T889eb+k86zUjbX8SbR5OqVHfLHb3DgzyGc/7AdgxwVH1Va/h4HXh36fn2fTJOMmQ8M9MTLc13zjpcITk5YjimHWlxThjZ3MY+fJpGFbdbkPDkb04JTZ2zdm1iwl2Yg750lwZ69PTcflRPtfk/Faf5/ASxJCAYGmiCCy+2uPT7j1PR5MSoAsbvIXET2mSut5x0n+NBo7CAt2uexruoT7jICecjGvWm/bgh/aqoxy+KQKi8AgAzw2EQH6CSfzTFpzWm6cA47Hlj6QGR+Nn1OjCPCc=
    - secure: AEjAOTJ+1zdBzIJLaju8DRAr3o0tPhx1CGKcZCGXZMuj4Ueh/Keflpn3jTuwn95AVdZlnfZ+Pq2SWvnRvefLYCr/QG/Z3Dlgn+6pwfyxHeJWHyDKF1vW3WUU8SsnvikNwK2cezTSOHkSuVt35GTziLdhCbHp+XpIwc+9LWMm2uhW2Vlnz4ZeiV43YR2Q4OYNpS/lmR81A62xqkFfPdbRXyrxt/f+UjBp464ZeQDIKjfPOWqtPcf7sG3el8C/X33z3xjVETG+oWtWu1vrzmWpUcLoXpxQq/WVx5UN2JG3A5g3vwKybzT9FHtSQMxbK7ghcM6wdKd92mcEA8wYoyGAFNKjN54GO7Ir3ZjdFB0WRHFPMahgSV1gvM3HQKNK62HXH3FM9KG8jCnG0o6YDCMAw17QvaSGXUT7KUZbjw6dkG0fwrUS5jfowc+OgmCCH/xr/bZiK8KpFVVWFEh3zvlluN1nv3gEnXDYFUAB+aS75J/WIbmqi1ocNyr+mkBU70hO6LeykLnTERkzbWaDlhY1riBh3+7x5EPHduxlw+XGXM38/8mDD7c3zgIJuKWGrLDhWPekWSUky4xq141r82isFIAoz6m8vDOMfuJnFKH71TMYyDfGVmcwDH1nquyIxo0J6FadQ5xtPj5nuSbq6o33Z+OvO1af/W5+kSjSGwgyETU=
    - secure: mIV68Y693lnpQphSYS2PIdmXe2qpgpCjAQ0M4dwGin9miamB8I5/2dZ5cfOMhevTa6AUxJh1N9PWb1gfzR0aFVIVfRzjIj1E2GpFehMESIghuI6Kq9yqIE2TJsgdArGnUJZCPT9SUTQM5wIfBD/c7m2Zc2XGqXOmtdNhtZJ49n2WbstC3hWsfOJYk1zPrWLk14vJfIhSA0fY3lU14/2xdrde83pxrtEOAj1FbNNqutUtUlxaABT2Zc2pM+tn76JiaLEmP1fvK34Ot2ZK7VPXWqnHrgFZRgoXeagEki0lCiQu0Z0qvTSqlTprxrgjaQeqxEnmmFZfwwD48fXEUJHTe1SGWdhuRKbXjLE8pw55uSxgXPfFjvzP4lyiyLlfmTJNj7UNdIFsGKohgmLhM0XM+hwo17mTYdj/aU1ISX5ztw30HpMuAoqwAItncr64ByA7h38tWgk0VFlrZRw7VV2lyMl8HgJA0YMU3Udswqr3uxqfzKNi0OiH7oyLCQmvNKZMRuYDywvV8WG4b9w1M9o5sHdFc5vOT1lETdhlpsXkQhniloys5gX4tK2V1JeUsLbmHwn8oU9t8Ab+mqNf9+Masuutjw5uasZYTo7xxNGTLQq5SwvZvwcqvYolU6HbsRxF3+0u4uHE2zz50ae9hvsC6o6yKLe1ex4FSwbKKKg580o=
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/lib/node_modules
install:
  - npm i
script:
  - npm test
branches:
  only:
    - master
    - /^feature-.*/
after_success:
  - npm i codecov -g && codecov
before_deploy:
  - export NOW_ALIAS=pull
  - export PRIVATE_BASE64=$(openssl aes-256-cbc -K $encrypted_c408d5c1e9ea_key -iv $encrypted_c408d5c1e9ea_iv -in pk.pem.enc -d | base64)
  - npm i now -g
deploy:
  provider: script
  script: npm run travis:deploy-now
  on:
    branch: master
