name: Build and Push
on: 
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        version: '10.x'
    - run: npm ci
    - run: npm test
    - name: Build Docker Image
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      run: >
        docker build -t $CONTAINER_REGISTRY/${{ github.repository }} . \
          --build-arg VCS_REF=${{ github.sha }} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    - name: Login to Docker Registry
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: >
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $CONTAINER_REGISTRY
    - name: Push Docker Image
      env:
        CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      run: >
        docker push $CONTAINER_REGISTRY/${{ github.repository }}
